"""Regenerate indicative mass_report.csv from live transport assembly geometry."""

from __future__ import annotations

import csv
import math
import sys
from collections import defaultdict
from io import StringIO
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from stand_cad.geometry.analysis import (  # noqa: E402
    StabilityReportInputs,
    empty_case_mass_kg,
    indicative_tray_deflection_mm,
    indicative_tray_deflection_single_span_mm,
    mass_report_rows,
    part_mass_kg,
    plotter_mass_samples,
    stability_report_inputs,
    structural_mass_samples,
    weighted_centre_of_mass_mm,
)
from stand_cad.geometry.assembly import build_transport_assembly  # noqa: E402
from stand_cad.geometry.export import CONCEPT_REVISION  # noqa: E402
from stand_cad.geometry.hardware import (  # noqa: E402
    indicative_bracket_mass_kg,
    indicative_fastener_mass_kg,
    total_fastener_count,
)
from stand_cad.parameters import load_parameters  # noqa: E402

DEFAULT_PARAMETERS = REPO_ROOT / "config" / "parameters.yaml"
DEFAULT_VALIDATION_DIR = REPO_ROOT / "output" / "validation" / f"rev{CONCEPT_REVISION}"
DEFAULT_OUTPUT = DEFAULT_VALIDATION_DIR / "mass_report.csv"

_KNOWN_OTHER_EXCLUDED: tuple[tuple[str, str], ...] = (
    ("SLIDE-", "SLIDE-*"),
    ("VIBMOUNT-", "VIBMOUNT-*"),
    ("MAINS-INLET", "MAINS-INLET-001"),
    ("INTERLOCK-", "INTERLOCK-*"),
    ("EDGEGUARD-", "EDGEGUARD-*"),
)


def _present_other_excluded_category_labels(parts: dict) -> str:
    """List excluded (non-SHELF) category labels actually present in transport.parts."""
    other_ids = {
        part_id
        for part_id, record in parts.items()
        if record.verify_on_real_machine and not part_id.startswith("SHELF-")
    }
    labels: list[str] = []
    matched: set[str] = set()
    for prefix, label in _KNOWN_OTHER_EXCLUDED:
        hits = {part_id for part_id in other_ids if part_id.startswith(prefix)}
        if hits:
            labels.append(label)
            matched |= hits
    if other_ids - matched:
        labels.append("etc.")
    return ", ".join(labels) if labels else "(none)"


def write_mass_report(
    params_path: Path = DEFAULT_PARAMETERS,
    output_path: Path = DEFAULT_OUTPUT,
) -> dict[str, float]:
    """Build transport assembly and write mass_report.csv; return headline totals."""
    params = load_parameters(params_path)
    state = build_transport_assembly(params)
    parts = state.parts

    structural = empty_case_mass_kg(parts, params)
    excluded = [record for record in parts.values() if record.verify_on_real_machine]
    excluded_mass = sum(part_mass_kg(record, params) for record in excluded)
    shelf_mass = sum(
        part_mass_kg(record, params)
        for part_id, record in parts.items()
        if part_id.startswith("SHELF-")
    )
    all_total = sum(part_mass_kg(record, params) for record in parts.values())
    empty_plus_shelf = structural + shelf_mass
    fastener_kg = indicative_fastener_mass_kg(params)
    bracket_kg = indicative_bracket_mass_kg(params)

    rows = mass_report_rows(parts, params)
    mat_mass: dict[str, float] = defaultdict(float)
    for row in rows:
        mat_mass[row.material] += row.mass_kg
    dominant_material, dominant_mass = max(mat_mass.items(), key=lambda item: item[1])

    com_empty = weighted_centre_of_mass_mm(structural_mass_samples(parts, params))
    com_plot = weighted_centre_of_mass_mm(
        structural_mass_samples(parts, params) + plotter_mass_samples(parts, params)
    )
    com_ext = weighted_centre_of_mass_mm(
        structural_mass_samples(parts, params)
        + plotter_mass_samples(
            parts, params, lower_extension_mm=float(params.value("trays.lower_extension"))
        )
    )

    other_excluded = _present_other_excluded_category_labels(parts)
    header_lines = [
        f"# PLT-006 rev{CONCEPT_REVISION} indicative mass report — NOT authoritative for Gate G4",
        "# Method: single-face shell / open-section frame approximations from analysis.py",
        "# Generated by scripts/generate_mass_report.py from live mass_report_rows()",
        f"# Empty-case structural total (excludes all verify_on_real_machine=True parts, "
        f"{len(excluded)} parts / {excluded_mass:.3f} kg): {structural:.3f} kg",
        f"# Including modeled SHELF-* parts only (adds back ~{shelf_mass:.3f} kg of the "
        f"excluded mass): {empty_plus_shelf:.3f} kg",
        f"# Other excluded categories ({other_excluded}) are physically present but omitted "
        "from both headline totals; full all-parts sum via part_mass_kg over transport registry",
        f"# Full all-parts indicative total: {all_total:.3f} kg",
        f"# D-061 indicative bought-in fasteners (not in structural total): {fastener_kg:.3f} kg "
        f"({total_fastener_count(params)} screws — lengths/torques to_measure)",
        f"# D-061 indicative corner brackets (20×20×2 mm L-gusset, not all modeled as solids): "
        f"{bracket_kg:.3f} kg",
        "# Ceiling 12 kg; target band 9-11 kg applies to the structural total excluding "
        "verify_on_real_machine parts",
        f"# Dominance: {dominant_material} ({dominant_mass:.3f} kg)",
        f'"# CoM empty case (mm): x={com_empty[0]:.1f}, '
        f'y={com_empty[1]:.1f}, z={com_empty[2]:.1f}"',
        f'"# CoM case + 2 plotters (mm): x={com_plot[0]:.1f}, '
        f'y={com_plot[1]:.1f}, z={com_plot[2]:.1f}"',
        f'"# CoM lower tray extended + 2 plotters (mm): x={com_ext[0]:.1f}, y={com_ext[1]:.1f}, '
        f'z={com_ext[2]:.1f}"',
        "",
    ]

    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        ["part_id", "material", "volume_mm3", "density_kg_m3", "density_source", "mass_kg"]
    )
    for row in rows:
        writer.writerow(
            [
                row.part_id,
                row.material,
                f"{row.volume_mm3:.1f}",
                row.density_kg_m3,
                row.density_source,
                f"{row.mass_kg:.4f}",
            ]
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = buf.getvalue()
    output_path.write_text("".join(f"{line}\n" for line in header_lines) + body, encoding="utf-8")

    return {
        "structural_kg": structural,
        "excluded_count": float(len(excluded)),
        "excluded_kg": excluded_mass,
        "empty_plus_shelf_kg": empty_plus_shelf,
        "all_parts_kg": all_total,
        "row_count": float(len(rows)),
    }


def write_stability_report(
    params_path: Path = DEFAULT_PARAMETERS,
    output_path: Path | None = None,
) -> Path:
    """Write stability_report.md from live analysis helpers."""
    if output_path is None:
        output_path = DEFAULT_VALIDATION_DIR / "stability_report.md"
    params = load_parameters(params_path)
    state = build_transport_assembly(params)
    parts = state.parts
    lower = stability_report_inputs(params, parts, extended_level="lower")
    upper = stability_report_inputs(params, parts, extended_level="upper")
    minimum = float(params.value("stability.tip_factor_min"))
    rev = CONCEPT_REVISION

    def _tier_section(report: StabilityReportInputs) -> list[str]:
        tier_label = "Lower" if report.extended_level == "lower" else "Upper"
        if report.applicable:
            title = f"{tier_label} tray extended"
        elif report.extension_mm <= 0.0:
            title = f"{tier_label} tray (zero travel / fixed)"
        else:
            title = f"{tier_label} tray extended (tip factor not applicable)"
        other_idx = 1 if report.extended_level == "upper" else 2
        other_mass = params.plotter_mass_kg(other_idx)
        if report.applicable and math.isfinite(report.factor):
            tip_line = f"- **Tip factor: {report.factor:.3f}** (minimum {minimum})"
        elif report.extension_mm <= 0.0:
            tip_line = (
                "- **Tip factor: N/A — not applicable "
                "(D-076; zero travel / no overhang tip case)**"
            )
        else:
            tip_line = (
                "- **Tip factor: N/A — not applicable "
                "(non-finite; overturn moment ≤ 0 / insufficient overturn arm)**"
            )
        if report.applicable and math.isfinite(report.legacy_factor):
            legacy_line = (
                f"- Legacy pre-D-039 factor (mass-cancelling model): "
                f"{report.legacy_factor:.3f}"
            )
        elif report.extension_mm <= 0.0:
            legacy_line = "- Legacy pre-D-039 factor: N/A (zero travel)"
        else:
            legacy_line = (
                "- Legacy pre-D-039 factor: N/A "
                "(non-finite / insufficient overturn arm)"
            )
        return [
            f"## {title} (pivot: {report.pivot_edge})",
            "",
            f"- Extension: {report.extension_mm:.0f} mm "
            f"(`trays.{report.extended_level}_extension`)",
            f"- Pivot Y: {report.pivot_y_mm:.1f} mm (`hardware.foot_diameter_mm`/2)",
            f"- Moving mass: {report.moving_mass_kg:.3f} kg "
            "(extended tier tray panel + that tier's plotter only)",
            f"- Moving CoG Y at rest: {report.moving_cog_y_rest_mm:.1f} mm",
            f"- Moving CoG Y fully extended: {report.moving_cog_y_extended_mm:.1f} mm "
            f"(rest − extension; sign matches `apply_tray_extension`)",
            f"- Stationary mass: {report.stationary_mass_kg:.3f} kg "
            f"(computed structural {report.structural_mass_kg:.3f} kg − moving tray panel "
            f"+ other plotter {other_mass:.1f} kg)",
            f"- Stationary CoG Y: {report.stationary_cog_y_mm:.1f} mm",
            f"- Restore arm: {report.restore_arm_mm:.1f} mm "
            f"(stationary CoG Y − pivot Y)",
            f"- Overturn arm: {report.overturn_arm_mm:.1f} mm "
            f"(pivot Y − moving CoG Y extended)",
            f"- Restore moment: {report.restore_moment_n_mm:.0f} N·mm",
            f"- Overturn moment: {report.overturn_moment_n_mm:.0f} N·mm",
            tip_line,
            legacy_line,
            "",
        ]

    lines = [
        f"# PLT-010 rev{rev} indicative stability report — NOT authoritative for Gate G4",
        "",
        "Split stationary/moving mass static-moment model (D-039): one tray fully extended,",
        "both plotters installed, structural mass from live "
        "`empty_case_mass_for_stability_kg()` (geometric `empty_case_mass_kg()` + D-061 "
        "indicative fastener/bracket roll-up at structural CoM) — not the "
        "`mass_targets.empty_case_target_max_kg` placeholder used by the retired model.",
        "",
        "### Model correction (D-039)",
        "",
        "The pre-rev10 model applied identical `total_mass` to both restore and overturn",
        "moments, so mass cancelled algebraically and only extension ratio mattered.",
        "Both tiers slide toward the front (Y=0) per `apply_tray_extension`; pivot is the",
        "front foot line for both tiers.",
        "",
        *_tier_section(lower),
        *_tier_section(upper),
        "## Operational media pass-through (D-028 — structural, not open)",
        "",
        f"- Manufacturer clearance each end: "
        f"{float(params.value('operational.material_travel_clearance_mm')):.0f} mm",
        f"- Governing machine depth: "
        f"{float(params.value('plotter.physical_depth')):.0f} mm (Cameo 4)",
        f"- Required linear pass-through: {params.pass_through_depth_required_mm():.0f} mm "
        f"(356 + 195 + 356 = 907)",
        (
            f"- Case depth: {float(params.value('case.depth')):.0f} mm → "
            "**closed niche is storage/transport only**"
        ),
        "- Active cutting requires front and rear media openings "
        f"({float(params.value('media_path.clear_width')):.0f}×"
        f"{float(params.value('media_path.slot_height_target')):.0f} mm rear channels at L1/L2 "
        f"via MEDIA-SUPPORT-L1-001 / MEDIA-SUPPORT-L2-001) "
        "and/or tray extension.",
        f"- Closed-tray clearances (D-033 aligned front faces, setback removed): plotter 1 front "
        f"{params.material_travel_clearance_front_mm(1):.0f} mm; plotter 2 rear "
        f"{params.material_travel_clearance_rear_mm(2):.0f} mm",
        "",
        "Generated by `scripts/generate_mass_report.py` from `stability_report_inputs()`.",
        "",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_deflection_report(
    params_path: Path = DEFAULT_PARAMETERS,
    output_path: Path | None = None,
) -> Path:
    """Write deflection_report.md from live analysis helpers."""
    if output_path is None:
        output_path = DEFAULT_VALIDATION_DIR / "deflection_report.md"
    params = load_parameters(params_path)
    load_kg = float(params.value("trays.design_load_kg"))
    span_mm = float(params.value("plotter.physical_width"))
    half_span_mm = span_mm / 2
    width_mm = float(params.value("plotter.physical_depth"))
    thickness_mm = params.tray_panel_thickness_mm
    e_mpa = float(params.value("materials.tray_panel_youngs_modulus_mpa"))
    ceiling = float(params.value("trays.deflection_max_mm"))
    deflection_old = indicative_tray_deflection_single_span_mm(params)
    deflection = indicative_tray_deflection_mm(params)
    e_fail_mpa = e_mpa * deflection / ceiling
    rev = CONCEPT_REVISION
    lines = [
        f"# PLT-006 rev{rev} indicative tray deflection report — NOT authoritative for Gate G4",
        "",
        "Hand-check beam models only (not FEA). Panel thickness and E unchanged from rev6;",
        "fix is a third centre slide rail (D-035) changing the support condition.",
        "",
        "## Before — two-rail single-span model (rev6 baseline)",
        "",
        "Simply-supported uniform load across full rail-to-rail span:",
        "",
        "- Span (rail-to-rail across X): `plotter.physical_width` = "
        f"{span_mm:.0f} mm",
        "- Load width (distributed along Y): `plotter.physical_depth` = "
        f"{width_mm:.0f} mm",
        f"- Panel thickness: {thickness_mm:.1f} mm (midpoint of tray_panel_thickness range)",
        f"- Design load: {load_kg:.0f} kg (`trays.design_load_kg`)",
        f"- E: {e_mpa:.0f} MPa (`materials.tray_panel_youngs_modulus_mpa`, to_measure)",
        "",
        f"**Mid-span deflection (two rails): {deflection_old:.3f} mm**",
        f"TZ ceiling: {ceiling:.1f} mm (`trays.deflection_max_mm`, TZ line 184)",
        "",
        "Verdict (rev6): **ceiling NOT met** — carried forward as honest history.",
        "",
        "## After — three-rail model with conservative half-span simplification",
        "",
        "Centre slide at tray mid-X (`SLIDE-*-CENTER-001`) bisects the span into two",
        f"~{half_span_mm:.0f} mm half-spans. Conservative simplification: each half-span",
        "modelled as an **independent** simply-supported beam carrying half the total UDL",
        "(P/2 on L/2), ignoring elastic continuity at the centre support. A true",
        "two-equal-span continuous beam would give ~2.4× **lower** peak deflection — this",
        "model is conservative, not optimistic.",
        "",
        f"- Effective half-span: {half_span_mm:.0f} mm (span/2)",
        f"- Effective load per half-span: {load_kg / 2:.1f} kg (design_load/2)",
        f"- Panel thickness: {thickness_mm:.1f} mm (unchanged)",
        f"- E: {e_mpa:.0f} MPa (unchanged, to_measure)",
        "",
        f"**Mid-span deflection (three rails, conservative): {deflection:.3f} mm**",
        f"TZ ceiling: {ceiling:.1f} mm",
        "",
        "Verdict: **ceiling met** under the current indicative conservative model.",
        "E remains `to_measure` — no silent retuning.",
        "",
        "## E-sensitivity (three-rail conservative model)",
        "",
        f"Since δ ∝ 1/E, this construction fails the {ceiling:.1f} mm ceiling only if measured",
        f"E falls below **{e_fail_mpa:.0f} MPa** ({e_mpa:.0f} × {deflection:.3f}/{ceiling:.1f})",
        f"— roughly a {e_mpa / e_fail_mpa:.1f}× drop from the assumed {e_mpa:.0f} MPa.",
        "Record measured E against this threshold before Gate G4 structural sign-off.",
        "",
        "Generated by `scripts/generate_mass_report.py` from `indicative_tray_deflection_mm()`.",
        "",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_all_reports(
    params_path: Path = DEFAULT_PARAMETERS,
    validation_dir: Path = DEFAULT_VALIDATION_DIR,
) -> dict[str, float]:
    """Write mass, stability, and deflection reports under validation_dir."""
    mass_path = validation_dir / "mass_report.csv"
    totals = write_mass_report(params_path, mass_path)
    write_stability_report(params_path, validation_dir / "stability_report.md")
    write_deflection_report(params_path, validation_dir / "deflection_report.md")
    return totals


def main() -> None:
    totals = write_all_reports()
    print(f"Wrote {DEFAULT_OUTPUT}")
    print(f"Wrote {DEFAULT_VALIDATION_DIR / 'stability_report.md'}")
    print(f"Wrote {DEFAULT_VALIDATION_DIR / 'deflection_report.md'}")
    print(
        f"structural={totals['structural_kg']:.3f} kg, "
        f"rows={int(totals['row_count'])}, "
        f"all_parts={totals['all_parts_kg']:.3f} kg"
    )


if __name__ == "__main__":
    main()
