"""Regenerate indicative mass_report.csv from live transport assembly geometry."""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from io import StringIO
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from stand_cad.geometry.analysis import (  # noqa: E402
    empty_case_mass_kg,
    indicative_tray_deflection_mm,
    mass_report_rows,
    part_mass_kg,
    plotter_mass_samples,
    stability_report_inputs,
    structural_mass_samples,
    weighted_centre_of_mass_mm,
)
from stand_cad.geometry.assembly import build_transport_assembly  # noqa: E402
from stand_cad.geometry.export import CONCEPT_REVISION  # noqa: E402
from stand_cad.parameters import load_parameters  # noqa: E402

DEFAULT_PARAMETERS = REPO_ROOT / "config" / "parameters.yaml"
DEFAULT_VALIDATION_DIR = REPO_ROOT / "output" / "validation" / f"rev{CONCEPT_REVISION}"
DEFAULT_OUTPUT = DEFAULT_VALIDATION_DIR / "mass_report.csv"


def write_mass_report(
    params_path: Path = DEFAULT_PARAMETERS,
    output_path: Path = DEFAULT_OUTPUT,
) -> dict[str, float]:
    """Build transport assembly and write mass_report.csv; return headline totals."""
    params = load_parameters(params_path)
    state = build_transport_assembly(params)
    parts = state.parts

    structural = empty_case_mass_kg(parts, params)
    excluded = [record for record in parts.values() if record.verify_on_real_machine]
    excluded_mass = sum(part_mass_kg(record, params) for record in excluded)
    shelf_mass = sum(
        part_mass_kg(record, params)
        for part_id, record in parts.items()
        if part_id.startswith("SHELF-")
    )
    all_total = sum(part_mass_kg(record, params) for record in parts.values())
    empty_plus_shelf = structural + shelf_mass

    rows = mass_report_rows(parts, params)
    mat_mass: dict[str, float] = defaultdict(float)
    for row in rows:
        mat_mass[row.material] += row.mass_kg
    dominant_material, dominant_mass = max(mat_mass.items(), key=lambda item: item[1])

    com_empty = weighted_centre_of_mass_mm(structural_mass_samples(parts, params))
    com_plot = weighted_centre_of_mass_mm(
        structural_mass_samples(parts, params) + plotter_mass_samples(parts, params)
    )
    com_ext = weighted_centre_of_mass_mm(
        structural_mass_samples(parts, params)
        + plotter_mass_samples(
            parts, params, lower_extension_mm=float(params.value("trays.lower_extension"))
        )
    )

    header_lines = [
        f"# PLT-006 rev{CONCEPT_REVISION} indicative mass report — NOT authoritative for Gate G4",
        "# Method: single-face shell / open-section frame approximations from analysis.py",
        "# Generated by scripts/generate_mass_report.py from live mass_report_rows()",
        f"# Empty-case structural total (excludes all verify_on_real_machine=True parts, "
        f"{len(excluded)} parts / {excluded_mass:.3f} kg): {structural:.3f} kg",
        f"# Including modeled SHELF-* parts only (adds back ~{shelf_mass:.3f} kg of the "
        f"excluded mass): {empty_plus_shelf:.3f} kg",
        "# Other excluded categories (SLIDE-*, MAINS-INLET-001, INTERLOCK-*, EDGEGUARD-*, "
        "VIBMOUNT-*, etc.) are physically present but omitted from both headline totals; "
        "full all-parts sum via part_mass_kg over transport registry",
        f"# Full all-parts indicative total: {all_total:.3f} kg",
        "# Ceiling 12 kg; target band 9-11 kg applies to the structural total excluding "
        "verify_on_real_machine parts",
        f"# Dominance: {dominant_material} ({dominant_mass:.3f} kg)",
        f'"# CoM empty case (mm): x={com_empty[0]:.1f}, '
        f'y={com_empty[1]:.1f}, z={com_empty[2]:.1f}"',
        f'"# CoM case + 2 plotters (mm): x={com_plot[0]:.1f}, '
        f'y={com_plot[1]:.1f}, z={com_plot[2]:.1f}"',
        f'"# CoM lower tray extended + 2 plotters (mm): x={com_ext[0]:.1f}, y={com_ext[1]:.1f}, '
        f'z={com_ext[2]:.1f}"',
        "",
    ]

    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        ["part_id", "material", "volume_mm3", "density_kg_m3", "density_source", "mass_kg"]
    )
    for row in rows:
        writer.writerow(
            [
                row.part_id,
                row.material,
                f"{row.volume_mm3:.1f}",
                row.density_kg_m3,
                row.density_source,
                f"{row.mass_kg:.4f}",
            ]
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = buf.getvalue()
    output_path.write_text("".join(f"{line}\n" for line in header_lines) + body, encoding="utf-8")

    return {
        "structural_kg": structural,
        "excluded_count": float(len(excluded)),
        "excluded_kg": excluded_mass,
        "empty_plus_shelf_kg": empty_plus_shelf,
        "all_parts_kg": all_total,
        "row_count": float(len(rows)),
    }


def write_stability_report(
    params_path: Path = DEFAULT_PARAMETERS,
    output_path: Path | None = None,
) -> Path:
    """Write stability_report.md from live analysis helpers."""
    if output_path is None:
        output_path = DEFAULT_VALIDATION_DIR / "stability_report.md"
    params = load_parameters(params_path)
    lower = stability_report_inputs(params, extended_level="lower")
    upper = stability_report_inputs(params, extended_level="upper")
    minimum = float(params.value("stability.tip_factor_min"))
    rev = CONCEPT_REVISION
    lines = [
        f"# PLT-006 rev{rev} indicative stability report — NOT authoritative for Gate G4",
        "",
        "Static tip-over moment model: one tray fully extended, both plotters installed,",
        "empty-case mass from `mass_targets.empty_case_target_max_kg` (concept placeholder).",
        "",
        "## Lower tray extended (pivot: front foot line Y=0)",
        "",
        f"- Extension: {lower.extension_mm:.0f} mm (`trays.lower_extension`)",
        f"- Total mass: {lower.total_mass_kg:.3f} kg (empty {lower.empty_mass_kg:.1f} + "
        f"{lower.plotter_count}× plotter {lower.plotter_mass_kg:.1f} kg)",
        f"- Restore arm: {lower.restore_arm_mm:.1f} mm (support_y {lower.support_y_mm:.1f} − "
        f"foot inset {lower.foot_inset_mm:.1f})",
        f"- Overturn arm: {lower.overturn_arm_mm:.1f} mm (extension/2)",
        f"- Restore moment: {lower.restore_moment_n_mm:.0f} N·mm",
        f"- Overturn moment: {lower.overturn_moment_n_mm:.0f} N·mm",
        f"- **Tip factor: {lower.factor:.3f}** (minimum {minimum})",
        "",
        "## Upper tray extended (pivot: rear foot line Y=depth)",
        "",
        f"- Extension: {upper.extension_mm:.0f} mm (`trays.upper_extension`)",
        f"- **Tip factor: {upper.factor:.3f}** (minimum {minimum})",
        "",
        "## Operational media pass-through (D-028 — structural, not open)",
        "",
        f"- Manufacturer clearance each end: "
        f"{float(params.value('operational.material_travel_clearance_mm')):.0f} mm",
        f"- Governing machine depth: "
        f"{float(params.value('plotter.physical_depth')):.0f} mm (Cameo 4)",
        f"- Required linear pass-through: {params.pass_through_depth_required_mm():.0f} mm "
        f"(356 + 195 + 356 = 907)",
        (
            f"- Case depth: {float(params.value('case.depth')):.0f} mm → "
            "**closed niche is storage/transport only**"
        ),
        "- Active cutting requires front and rear media openings (330 mm rear slots at L1/L2) "
        "and/or tray extension plus external rear supports (`services.rearsupport_*`).",
        f"- Closed-tray clearances (D-033 aligned front faces, setback removed): plotter 1 front "
        f"{params.material_travel_clearance_front_mm(1):.0f} mm; plotter 2 rear "
        f"{params.material_travel_clearance_rear_mm(2):.0f} mm",
        "",
        "Generated by `scripts/generate_mass_report.py` from `stability_report_inputs()`.",
        "",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_deflection_report(
    params_path: Path = DEFAULT_PARAMETERS,
    output_path: Path | None = None,
) -> Path:
    """Write deflection_report.md from live analysis helpers."""
    if output_path is None:
        output_path = DEFAULT_VALIDATION_DIR / "deflection_report.md"
    params = load_parameters(params_path)
    load_kg = float(params.value("trays.design_load_kg"))
    span_mm = float(params.value("plotter.physical_width"))
    width_mm = float(params.value("plotter.physical_depth"))
    thickness_mm = params.tray_panel_thickness_mm
    e_mpa = float(params.value("materials.tray_panel_youngs_modulus_mpa"))
    ceiling = float(params.value("trays.deflection_max_mm"))
    deflection = indicative_tray_deflection_mm(params)
    rev = CONCEPT_REVISION
    lines = [
        f"# PLT-006 rev{rev} indicative tray deflection report — NOT authoritative for Gate G4",
        "",
        "Simply-supported uniform-load beam (concept hand-check only, not FEA):",
        "",
        "- Span (rail-to-rail across X): `plotter.physical_width` = "
        f"{span_mm:.0f} mm",
        "- Load width (distributed along Y): `plotter.physical_depth` = "
        f"{width_mm:.0f} mm",
        f"- Panel thickness: {thickness_mm:.1f} mm (midpoint of tray_panel_thickness range)",
        f"- Design load: {load_kg:.0f} kg (`trays.design_load_kg`)",
        f"- E: {e_mpa:.0f} MPa (`materials.tray_panel_youngs_modulus_mpa`, to_measure)",
        "",
        f"**Mid-span deflection: {deflection:.3f} mm**",
        f"TZ ceiling: {ceiling:.1f} mm (`trays.deflection_max_mm`)",
        "",
        "Verdict: **ceiling NOT met** under current unsourced E — requires measured stiffness,",
        "tray redesign, or slide/support review. Do not retune E silently.",
        "",
        "Generated by `scripts/generate_mass_report.py` from `indicative_tray_deflection_mm()`.",
        "",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_all_reports(
    params_path: Path = DEFAULT_PARAMETERS,
    validation_dir: Path = DEFAULT_VALIDATION_DIR,
) -> dict[str, float]:
    """Write mass, stability, and deflection reports under validation_dir."""
    mass_path = validation_dir / "mass_report.csv"
    totals = write_mass_report(params_path, mass_path)
    write_stability_report(params_path, validation_dir / "stability_report.md")
    write_deflection_report(params_path, validation_dir / "deflection_report.md")
    return totals


def main() -> None:
    totals = write_all_reports()
    print(f"Wrote {DEFAULT_OUTPUT}")
    print(f"Wrote {DEFAULT_VALIDATION_DIR / 'stability_report.md'}")
    print(f"Wrote {DEFAULT_VALIDATION_DIR / 'deflection_report.md'}")
    print(
        f"structural={totals['structural_kg']:.3f} kg, "
        f"rows={int(totals['row_count'])}, "
        f"all_parts={totals['all_parts_kg']:.3f} kg"
    )


if __name__ == "__main__":
    main()
